### ISSUE TITLE
User Registration Flow

### ISSUE THREAD

**Issue by foohonpie** [pbbg/pbbg.com#17]
Depends on https://github.com/pbbg/api.pbbg.com/pull/9.  Once that is ready, we'll need:

## UI

It would be great if we could have /register overlay a modal on the home page, with a registration nav button triggering the same modal.  

The form itself is just the basic form, nothing noteworthy.  Please post here with any questions.

## Fields and Validation

Fields and FE validation are:
  * `name`
    * required
    * alphanum
  * `email_address`
    * required
    * email format
  * `password`
    * required
    * min:8
  * `confirm_password`
    * required
    * must match `password`

We should catch errors before sending to the API, which will do its own validation.

## Post-Register

Upon successful registration, a Bearer token will be received to be passed in subsequent calls.

The user should land on /dashboard.  I am open to suggestions if we think a different route name is better.

The /dashboard page should send request with Bearer token to `GET /user`
   * If auth fails, send to home page with error
   * If auth succeeds, render simple dump of the return data

There is no design yet for /dashboard; the goal for this ticket is to get the flow functional.

Please post here with any questions.  Thanks!

**Comment by bpkennedy** [comment]
Compiling some questions:
* I will make the large screen overlay act so that the user can click on the opaque area to close it OR click a close icon on the modal itself.  For mobile screens, what do you think about a fullscreen modal (due to the low screen real estate and it being a form....)?
* For the token - how do we want to store that when the user comes back to the website.  Will it be in session storage, local storage, a cookie?
* From the api, if the user picks an existing email and therefore gets a 422 back (or any other 400 or 422 for other reasons) from the api where on the page do those validation messages appear?

General questions:
So, local development and Github Actions CI will both be using the `https://dev-api.pbbg.com` endpoint for getting data, yes?  I'll use that for the time being, but we may at some point need to look into how to stand that up locally for each developer.  If it goes down and the UI is becoming auth-protected then development would come to a standstill during the down-time.

**Comment by foohonpie** [comment]
A fullscreen modal sounds like a good idea, good call.

I'm not sure on the token storage, do you see specific pros/cons between the options?

For the errors, the messages should be keyed by field, so they can ideally be shown with their respective inputs.

> General questions

Yeah hitting the dev API should be fine, I'd like to treat it as if it's a stable 3rd party service.

**Comment by foohonpie** [comment]
Great work, @bpkennedy!
